export const SET_CONTACTS = "SET_CONTACTS";
export const CONTACT_ALERT = "CONTACT_ALERT";

export const SET_TESTIMONIAL = "SET_TESTIMONIAL";
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL";
export const SETUPDATE_TESTIMONIAL = "SETUPDATE_TESTIMONIAL";
export const TESTIMONIAL_LOADING = "TESTIMONIAL_LOADING";
export const TESTIMONIAL_ALERT = "TESTIMONIAL_ALERT";
export const ADDTESTIMONIAL_LOADING = "ADDTESTIMONIAL_LOADING";

export const SET_EOM = "SET_EOM";
export const SET_EOMADMIN = "SET_EOMADMIN";
export const EOM_ALERT = "EOM_ALERT";
export const DELETE_EOM = "DELETE_EOM";
export const SETUPDATE_EOM = "SETUPDATE_EOM";
export const EOM_LOADING = "EOM_LOADING";
export const ADDEOM_LOADING = "ADDEOM_LOADING";

export const SIGNUP = "SIGNUP";
export const SIGNIN = "SIGNIN";

export const SETCLIENT_CAROUSEL = "CLIENT_CAROUSEL";
export const SETUPDATECLIENT_CAROUSEL = "SETUPDATECLIENT_CAROUSEL";
export const CLIENT_CAROUSELALERT = "CLIENT_CAROUSELALERT";
export const DELETECLIENT_CAROUSEL = "DELETECLIENT_CAROUSEL";
export const CLIENTCAROUSEL_LOADING = "CLIENTCAROUSEL_LOADING";
export const ADDCLIENT_LOADING = "ADDCLIENT_LOADING";

export const SET_TEAM = "SET_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";
export const SETUPDATE_TEAM = "SETUPDATE_TEAM";
export const TEAM_LOADING = "TEAM_LOADING";
export const TEAM_ALERT = "TEAM_ALERT";
export const ADDTEAM_LOADING = "ADDTEAM_LOADING";
