export const SET_CONTACTS = "SET_CONTACTS";
export const CONTACT_ALERT = "CONTACT_ALERT";

export const SET_TESTIMONIAL = "SET_TESTIMONIAL";
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL";
export const TESTIMONIAL_ERROR = "TESTIMONIAL_ERROR";
export const SETUPDATE_TESTIMONIAL = "SETUPDATE_TESTIMONIAL";
export const TESTIMONIAL_LOADING = "TESTIMONIAL_LOADING";

export const SET_EOM = "SET_EOM";
export const SET_EOMADMIN = "SET_EOMADMIN";
export const EOM_ALERT = "EOM_ALERT";
export const DELETE_EOM = "DELETE_EOM";
export const SETUPDATE_EOM = "SETUPDATE_EOM";
export const EOM_LOADING = "EOM_LOADING";

export const SIGNUP = "SIGNUP";
export const SIGNIN = "SIGNIN";

export const SETCLIENT_CAROUSEL = "CLIENT_CAROUSEL";
export const SETUPDATECLIENT_CAROUSEL = "SETUPDATECLIENT_CAROUSEL";
export const CLIENT_CAROUSELALERT = "CLIENT_CAROUSELALERT";
export const DELETECLIENT_CAROUSEL = "DELETECLIENT_CAROUSEL";
export const CLIENTCAROUSEL_LOADING = "CLIENTCAROUSEL_LOADING";
